config/routes.rb
Rails.application.routes.draw do
  resources :admins, :controller => "admins"
  match 'admins/:id' => 'admins#destroy', :via => [:get, :post], :as => :admin_destroy
  match 'admins/:id/edit' => 'admins#edit', :via => [:get, :post], :as => :admin_edit
  get 'welcome/index'
  resources :stores do
    resources :historia_tiendas
    resources :empleados do
      resources :historia_empleados
    end
  end
  devise_for :users, :controllers => { registrations: 'registro' }

  root 'welcome#index'

end

app/views/admins/_form.html.erb
<%= form_for(@user, :url => { :action => "create" } ) do |f| %>
  <div class="field">
    <%= f.label :email, "E-mail" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>
  <div class="field doscientos">
    <%= f.label :tipo, "Privilegio" %><br />
    <%= f.select :tipo do%>
      <%= content_tag(:option, "Usuario", value: "1") %>
      <%= content_tag(:option, "Administrador", value: "2") %>
    <%end%>
  </div>
  <div class="field">
    <%= f.label :nombre, "Nombre de usuairo" %><br />
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :password, "Contraseña" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirma el password"%><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>
  <div class="actions">
    <%= f.submit  "Guardar Datos de usuario" ,"data-inline"=>"true"%>
  </div>
<% end %>

app/views/admins/edit.html.erb
  <div class="col-md-8 col-md-offset-2">
  <h2 class="proyect_name alert alert-info">
    <strong class="center">Modificar usuario</strong> 
  </h2>
  <%= link_to ' Regresar', admins_path, "data-role" => "button",
   "data-inline"=>"true"%>
  <%= form_for(@user, :url => { :action => "update" } ) do |f| %>
  <div class="field">
    <%= f.label :email , "Correo electronico *"%><br>
    <%= f.email_field :email, autofocus: true ,class: "form-control"%>
  </div>
  <div class="field doscientos">
    <%= f.label :tipo, "Privilegio" %><br />
    <%= f.select :tipo do%>
      <%= content_tag(:option, "Usuario", value: "1") %>
      <%= content_tag(:option, "Administrador", value: "2") %>
    <%end%>
  </div>
  <div class="field">
    <%= f.label :nombre, "Nombre de usuairo" %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :password , "Contraseña"%>
    <% if @minimum_password_length %>
    <em>(Minímo <%= @minimum_password_length %> caracteres)</em>
    <% end %><br>
    <%= f.password_field :password%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation , "Confirma la Contraseña"%><br>
    <%= f.password_field :password_confirmation%>
  </div>
  <div class="actions">
    <%= f.submit  "Guardar Datos de usuario" , "data-inline" => "true"%>
  </div>
<% end %>
</div>

app/views/admins/index.html.erb
<h2 class="alert alert-danger text-center">
    <strong>Administracion de Usuarios</strong> 
  </h2>
  
  <%= link_to ' Crear usuario', new_admin_path,  "data-role" => "button", "data-inline"=>"true" %>
  <%= link_to ' Regresar', root_path, "data-role" => "button", "data-inline"=>"true"%>
  <div class="table-responsive">
    <table class="table table-bordered ui-responsive" data-role="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Correo de usuario</th>
        <th>Privilegio</th>
      </tr>
    </thead>
      <tbody>

        <% @users.each do |user| %>
          <tr>
            <td><%= user.nombre %></td>
            <td><%= user.email %></td>
            <td> 
              <% if user.tipo == 2 %>
                Administrador
              <%else%>
                Normal
              <%end%>
            </td>
            <td>
              <%= link_to "Eliminar", admin_destroy_path(user), method: :delete, data: { confirm: "El usuario sera eliminado?" }%>
            </td>
            <td>
              <%= link_to "Editar", admin_edit_path(user), method: :edit%>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
    <%= link_to ' Regresar', root_path, "data-role" => "button",
     "data-inline"=>"true", "class" => "float_right"%>
  </div>

app/views/admins/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2 class="alert alert-info text-center">
    Registro de usuario
  </h2>
  <%= link_to 'regresar', admins_path, "data-role" => "button",
   "data-inline"=>"true"%> 
  <%= render "form"%> 
</div>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Back', admins_path %>