config/routes.rb
Rails.application.routes.draw do
  resources :admins, :controller => "admins"
  match 'admins/:id' => 'admins#destroy', :via => [:get, :post], :as => :admin_destroy
  match 'admins/:id/edit' => 'admins#edit', :via => [:get, :post], :as => :admin_edit
  get 'welcome/index'
  resources :stores do
    resources :historia_tiendas
    resources :empleados do
      resources :historia_empleados
    end
  end
  devise_for :users, :controllers => { registrations: 'registro' }

  root 'welcome#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :historia_tienda
  has_many :empleado
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :set_data, only: [:edit,:new]
  before_action :set_index, only: [:show]
  # GET /stores
  # GET /stores.json
  def index
    if current_user.is_admin?
      @stores = Store.all.order("user_id")
    else
      @stores = Store.where("user_id = ?", current_user.id)
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end
    def set_index
      @empleados = []
      @store.empleado.each do |x|
        x.historia_empleado.limit(4).order("created_at DESC").each do  |y|
          @empleados.push([y.titulo,y.log,y.fecha,x.nombre])
        end
      end
      @empleados = @empleados.sort_by {|key,id,fecha,nombre| fecha}.reverse!
    end
    def set_data 
      @users = User.all.map {|user| [user.nombre,user.id]}
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:user_id, :nombre, :direccion, :telefono)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> No se ha podido almacenar el registro por las siguientes razones:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input data-type="search" id="searchForUser" placeholder="Filtra el listado de usuarios">
  <div class="field">
    <%= f.label :user_id, "Dueño de la empresa" %>
    <%= f.select(:user_id,options_for_select(
        @users), {:include_blank => "Selecciona el dueño de la empresa"}, {required: 'true', "data-filter"=>"true", "data-input"=>"#searchForUser", id: "select_lider"}) %>
  </div>
  <div class="field">
    <%= f.label :nombre, "Nombre comercial de la tienda" %>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion, "Dirección de la empresa" %>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono, "Teléfono" %>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", "data-inline"=>"true" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1 class="alert alert-info text-center">Editar Tienda</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @store, 
	"data-inline"=>"true" , "data-role"=>"button" %>
<%= link_to 'Registrar', stores_path, 
	"data-inline"=>"true" , "data-role"=>"button" %>

app/views/stores/index.html.erb
<%if current_user.is_admin?%>
<%=link_to "Registrar tienda nueva", new_store_path,
"data-role" => "button", "data-inline"=>"true"%>
<%end%>
<form>
    <input id="filterTable-input" data-type="search">
</form>
<table data-role="table" id="movie-table" data-filter="true" data-input="#filterTable-input" class="ui-responsive">
<thead>
    <tr>
        <%if current_user.is_admin?%>
          <th data-priority="1">Dueño</th>
        <%end%>
        <th data-priority="2">Nombre de establecimiento</th>
        <th data-priority="3">Dirección</th>
        <th data-priority="4">Teléfono</th>
    </tr>
    </thead>
    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <%if current_user.is_admin?%>
            <td><%= store.user.nombre %></td>
          <%end%>
          <td><%= link_to store.nombre, store %></td>
          <td><%= store.direccion %></td>
          <td><%= store.telefono %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/stores/new.html.erb
<h1 class="alert alert-info text-center">Registrar una Tienda nueva</h1>

<%= render 'form' %>

<%= link_to 'Regresar', stores_path, 
	"data-inline"=>"true" , "data-role"=>"button" %>

app/views/stores/show.html.erb
<h1 class="alert alert-info text-center">
	<%=@store.nombre%>
</h1>
<div class="col-md-12 no_padding">
	<div class="col-md-4">
		<h4 class="alert alert-success text-center">
			Información de la empresa
		</h4>
		<ul class="list-group">
			<%if current_user.is_admin?%>
				<li class="list-group-item">
					Dueño de la empresa: <%=@store.user.nombre%>
				</li>
				<li class="list-group-item">
					Correo del dueño: <%=@store.user.email%>
				</li>
			<%end%>
			<li class="list-group-item">
				Dirección: <%=@store.direccion%>
			</li>
			<li class="list-group-item">
				Teléfono: 
				<a href="tel:<%=@store.telefono%>">
					<%=@store.telefono%>
				</a>
			</li>
			<li class="list-group-item">
				<%=link_to "Generar un reporte", 
				new_store_historia_tienda_path(@store), "data-role"=>"button",
				"data-inline"=>"true", "class" => "cienporciento" %>
			</li>
		</ul>
	</div>
	<div class="col-md-8">
		<h4 class="alert alert-danger text-center">
			Historial de la tienda
		</h4>
		<ul class="list-group sliderlist">
			<%@store.historia_tienda.limit(10).order("created_at DESC").each do |x|%>
				<li class="list-group-item">
					<h5 class="text-center negritas">
						<b><%=x.titulo%></b>
						<%if current_user.is_admin? || current_user.id == x.user_id%>
							<%= link_to([@store,x], method: :delete, 
								data: { confirm: 
								'Estas seguro de eliminar el registro?' }, class: "delete")  do %>	
								<i class="fa fa-times"></i>
							<%end%>
						<%end%>
					</h5>
					<p><%=x.log%></p>
					<p class="text_right blue">Fecha: <%=x.fecha%></p>
					<%if current_user.is_admin? || current_user.id == x.user_id%>
						<%=link_to "Editar",edit_store_historia_tienda_path(@store,x)%>
					<%end%>
				</li>
			<%end%>
		</ul>
	</div>
</div>
<div class="col-md-12 no_padding">
	<div class="col-md-4">
		<h4 class="alert alert-success text-center">
			Empleados Registrados
		</h4>
		<%= link_to "Registrar empleado", new_store_empleado_path(@store),
		"data-role" => "button", "data-inline" => "true"%>
		<ul class="list-group">
			<%@store.empleado.each do |x|%>
				<li class="list-group-item">
					<%=link_to x.nombre, [@store,x]%>	
				</li>
			<%end%>
		</ul>
	</div>
	<div class="col-md-8">
		<h4 class="alert alert-danger text-center">
			Historial de los usuarios
		</h4>
		<ul class="list-group sliderlist">
			<%@empleados.each do |x|%>
				<li class="list-group-item">
					<h5 class="text-center negritas">
						<b><%=x[0]%></b>
					</h5>
					<p>
						Responsable: <%=x[3]%><br>
						Reporte: <%=x[1]%>
					</p>
					<p class="text_right blue">Fecha: <%=x[2]%></p>
				</li>
			<%end%>
		</ul>
	</div>
</div>
<%if current_user.is_admin?%>
	<%= link_to 'Editar', edit_store_path(@store), 
	"data-inline"=>"true" , "data-role"=>"button"%>
<%end%>
<%= link_to 'Regresar', stores_path, 
	"data-inline"=>"true" , "data-role"=>"button"%>