config/routes.rb
Rails.application.routes.draw do
  resources :admins, :controller => "admins"
  match 'admins/:id' => 'admins#destroy', :via => [:get, :post], :as => :admin_destroy
  match 'admins/:id/edit' => 'admins#edit', :via => [:get, :post], :as => :admin_edit
  get 'welcome/index'
  resources :stores do
    resources :historia_tiendas
    resources :empleados do
      resources :historia_empleados
    end
  end
  devise_for :users, :controllers => { registrations: 'registro' }

  root 'welcome#index'

end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  belongs_to :store
  has_many :historia_empleado
  has_attached_file :foto, styles: {medium: "500x500"}
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]
  before_action :set_tienda
  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)
    @empleado.store_id = @tienda.id
    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @tienda, notice: 'Empleado registrado correctamente.' }
        format.json { render :show, status: :created, location: @tienda }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @tienda, notice: 'Empleado actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @tienda }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end
    def set_tienda
      @tienda = Store.find(params[:store_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :direccion, :telefono, :nacimiento, :puesto, :foto)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_for([@tienda,@empleado],:html => {:data => {:ajax => 'false'}}) do |f| %>
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> No se ha podido almacenar el usuario por las siguientes razones:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre, "Nombre del empleado"%>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :foto, "Fotografía del empleado"%>
    <%= f.file_field :foto %>
  </div>
  <div class="field">
    <%= f.label :direccion, "Dirección del Empleado" %>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono, "Celular" %>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :nacimiento, "Nacimiento"%>
    <%= f.date_field :nacimiento %>
  </div>
  <div class="field">
    <%= f.label :puesto , "Puesto"%>
    <%= f.text_field :puesto %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", "data-inline"=>"true" , "data-role"=>"button" %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Actualizar Información De Empleado</h1>

<%= link_to 'Regresar', [@tienda,@empleado], 
	"data-inline"=>"true" , "data-role"=>"button"%>

<%= render 'form' %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Nacimiento</th>
      <th>Puesto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.store %></td>
        <td><%= empleado.nombre %></td>
        <td><%= empleado.direccion %></td>
        <td><%= empleado.telefono %></td>
        <td><%= empleado.nacimiento %></td>
        <td><%= empleado.puesto %></td>
        <td><%= link_to 'Show', empleado %></td>
        <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>Empleado nuevo</h1>
<%= link_to 'Regresar', @tienda, 
	"data-inline"=>"true" , "data-role"=>"button" %>


<%= render 'form' %>

app/views/empleados/show.html.erb
<h3 class="alert alert-info text-center">
  Información del empleado
</h3>

<%= link_to 'Regresar', @tienda, "data-inline"=>"true",
"data-role" => "button" %>

<div class="col-md-12">
  <div class="col-md-4">
    <%=image_tag @empleado.foto.url(:medium), class: "cien"%>
  </div>
  <div class="col-md-8">
    <ul class="list-group">
      <li class="list-group-item">
        Nombre del empleado: 
        <%= @empleado.nombre %>
      </li>
      <li class="list-group-item">
        Tienda donde labora: 
        <%= @empleado.store.nombre %>
      </li>
      <li class="list-group-item">
        Direción: 
        <%= @empleado.direccion %>
      </li>
      <li class="list-group-item">
        Teléfono: 
        <%= @empleado.telefono %>
      </li>
      <li class="list-group-item">
        Puesto que desempeña: 
        <%= @empleado.puesto %>
      </li>
      <li class="list-group-item">
        Fecha de nacimiento: 
        <%= @empleado.nacimiento %>
      </li>
    </ul>
  </div>
  <%=link_to "Editar Información de empleado", 
    edit_store_empleado_path(@tienda,@empleado), "data-role" => "button",
    class: "aler alert-danger", "data-inline"=> "true"%>
</div>
<div class="col-md-12">
  <h4 class="alert alert-danger text-center">Historial del empleado</h4>
  <%=link_to "Registrar un reporte" ,new_store_empleado_historia_empleado_path(@tienda,@empleado), "data-role" => "button", "data-inline" => "true"%>
  <ul class="list-group sliderlist">
      <%@empleado.historia_empleado.limit(100).order("created_at DESC").each do |x|%>
        <li class="list-group-item">
          <h5 class="text-center negritas">
            <b><%=x.titulo%></b>
            <%if current_user.is_admin? || current_user.id == x.user_id%>
              <%= link_to([@tienda,@empleado,x], method: :delete, 
                data: { confirm: 
                'Estas seguro de eliminar el registro?' }, class: "delete")  do %>  
                <i class="fa fa-times"></i>
              <%end%>
            <%end%>
          </h5>
          <p><%=x.log%></p>
          <p class="text_right blue">Fecha: <%=x.fecha%></p>
          <%if current_user.is_admin? || current_user.id == x.user_id%>
            <%=link_to "Editar", edit_store_empleado_historia_empleado_path(@tienda,@empleado,x)%>
          <%end%>
        </li>
      <%end%>
    </ul>
</div>