config/routes.rb
Rails.application.routes.draw do
  resources :admins, :controller => "admins"
  match 'admins/:id' => 'admins#destroy', :via => [:get, :post], :as => :admin_destroy
  match 'admins/:id/edit' => 'admins#edit', :via => [:get, :post], :as => :admin_edit
  get 'welcome/index'
  resources :stores do
    resources :historia_tiendas
    resources :empleados do
      resources :historia_empleados
    end
  end
  devise_for :users, :controllers => { registrations: 'registro' }

  root 'welcome#index'

end

app/models/historia_empleado.rb
class HistoriaEmpleado < ActiveRecord::Base
  belongs_to :empleado
  belongs_to :user
end

app/controllers/historia_empleados_controller.rb
class HistoriaEmpleadosController < ApplicationController
  before_action :set_historia_empleado, only: [:show, :edit, :update, :destroy]
  before_action :set_data
  # GET /historia_empleados
  # GET /historia_empleados.json
  def index
    @historia_empleados = HistoriaEmpleado.all
  end

  # GET /historia_empleados/1
  # GET /historia_empleados/1.json
  def show
  end

  # GET /historia_empleados/new
  def new 
    @historia_empleado = HistoriaEmpleado.new
  end

  # GET /historia_empleados/1/edit
  def edit
  end

  # POST /historia_empleados
  # POST /historia_empleados.json
  def create
    @historia_empleado = HistoriaEmpleado.new(historia_empleado_params)
    @historia_empleado.empleado_id = @empleado.id
    @historia_empleado.user_id = current_user.id
    respond_to do |format|
      if @historia_empleado.save
        Notificacion.noticia_user(@tienda.user,@historia_empleado,
         current_user, @tienda,@empleado).deliver
        format.html { redirect_to [@tienda,@empleado], 
          notice: 'Historia Creada corretamente' }
        format.json { render :show, status: :created, location: [@tienda,@empleado] }
      else
        format.html { render :new }
        format.json { render json: @historia_empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historia_empleados/1
  # PATCH/PUT /historia_empleados/1.json
  def update
    respond_to do |format|
      if @historia_empleado.update(historia_empleado_params)
        Notificacion.noticia_user(@tienda.user,@historia_empleado,
         current_user, @tienda,@Empleado).deliver
        format.html { redirect_to [@tienda,@empleado] , notice: 'Historia actualizada correctamente' }
        format.json { render :show, status: :ok, location: [@tienda,@empleado]  }
      else
        format.html { render :edit }
        format.json { render json: @historia_empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historia_empleados/1
  # DELETE /historia_empleados/1.json
  def destroy
    @historia_empleado.destroy
    respond_to do |format|
      format.html { redirect_to [@tienda,@empleado], notice: 'Reporte de empleado eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historia_empleado
      @historia_empleado = HistoriaEmpleado.find(params[:id])
    end
    def set_data
      @tienda = Store.find(params[:store_id])
      @empleado = Empleado.find(params[:empleado_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def historia_empleado_params
      params.require(:historia_empleado).permit(:titulo, :fecha, :log)
    end
end

app/helpers/historia_empleados_helper.rb
module HistoriaEmpleadosHelper
end

app/views/historia_empleados/_form.html.erb
<%= form_for([@tienda,@empleado,@historia_empleado]) do |f| %>
  <% if @historia_empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@historia_empleado.errors.count, "error") %> No se ha podido almacenar el registro por las siguientes razones:</h2>

      <ul>
      <% @historia_empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo, "Nombre de Registro" %>
    <%= f.text_field :titulo %>
  </div>
  <div class="field doscientos">
    <%= f.label :fecha , "Fecha de reporte"%>
    <%= f.date_field :fecha %>
  </div>
  <div class="field">
    <%= f.label :log, "Reporte" %><br>
    <%= f.text_area :log %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", "data-inline" => "true" %>
  </div>
<% end %>

app/views/historia_empleados/edit.html.erb
<h1 class="alert alert-info text-center">Editar registro</h1>
<%= link_to 'Regresar', [@tienda,@empleado],
 "data-role" => "button", "data-inline" => "true" %>

<%= render 'form' %>

app/views/historia_empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Historia Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Empleado</th>
      <th>Titulo</th>
      <th>Fecha</th>
      <th>Log</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historia_empleados.each do |historia_empleado| %>
      <tr>
        <td><%= historia_empleado.empleado %></td>
        <td><%= historia_empleado.titulo %></td>
        <td><%= historia_empleado.fecha %></td>
        <td><%= historia_empleado.log %></td>
        <td><%= link_to 'Show', historia_empleado %></td>
        <td><%= link_to 'Edit', edit_historia_empleado_path(historia_empleado) %></td>
        <td><%= link_to 'Destroy', historia_empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historia empleado', new_historia_empleado_path %>

app/views/historia_empleados/new.html.erb
<h3 class="alert alert-info text-center">
	Levantar registro de empleado
</h3>
<%= link_to 'Regresar', [@tienda,@empleado],
 "data-role" => "button", "data-inline" => "true" %>
<%= render 'form' %>

app/views/historia_empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empleado:</strong>
  <%= @historia_empleado.empleado %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @historia_empleado.titulo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @historia_empleado.fecha %>
</p>

<p>
  <strong>Log:</strong>
  <%= @historia_empleado.log %>
</p>

<%= link_to 'Edit', edit_historia_empleado_path(@historia_empleado) %> |
<%= link_to 'Back', historia_empleados_path %>